# coding: utf-8

"""
    Onepanel Core

    Onepanel Core project API  # noqa: E501

    OpenAPI spec version: 1.0.0-beta1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.list_workflow_executions_response import ListWorkflowExecutionsResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestListWorkflowExecutionsResponse(unittest.TestCase):
    """ListWorkflowExecutionsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListWorkflowExecutionsResponse(self):
        """Test ListWorkflowExecutionsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.list_workflow_executions_response.ListWorkflowExecutionsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
