# coding: utf-8

"""
    Onepanel Core

    Onepanel Core project API  # noqa: E501

    OpenAPI spec version: 1.0.0-beta1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.delete_secret_key_response import DeleteSecretKeyResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestDeleteSecretKeyResponse(unittest.TestCase):
    """DeleteSecretKeyResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeleteSecretKeyResponse(self):
        """Test DeleteSecretKeyResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.delete_secret_key_response.DeleteSecretKeyResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
