# coding: utf-8

"""
    Onepanel Core

    Onepanel Core project API  # noqa: E501

    OpenAPI spec version: 1.0.0-beta1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.get_workflow_execution_metrics_response import GetWorkflowExecutionMetricsResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestGetWorkflowExecutionMetricsResponse(unittest.TestCase):
    """GetWorkflowExecutionMetricsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetWorkflowExecutionMetricsResponse(self):
        """Test GetWorkflowExecutionMetricsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.get_workflow_execution_metrics_response.GetWorkflowExecutionMetricsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
