# coding: utf-8

"""
    metric.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import core.api
from core.api.api.workflow_service_api import WorkflowServiceApi  # noqa: E501
from core.api.rest import ApiException


class TestWorkflowServiceApi(unittest.TestCase):
    """WorkflowServiceApi unit test stubs"""

    def setUp(self):
        self.api = core.api.api.workflow_service_api.WorkflowServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_archive_workflow_template(self):
        """Test case for archive_workflow_template

        """
        pass

    def test_create_workflow(self):
        """Test case for create_workflow

        """
        pass

    def test_create_workflow_template(self):
        """Test case for create_workflow_template

        """
        pass

    def test_create_workflow_template_version(self):
        """Test case for create_workflow_template_version

        """
        pass

    def test_get_workflow(self):
        """Test case for get_workflow

        """
        pass

    def test_get_workflow_logs(self):
        """Test case for get_workflow_logs

        """
        pass

    def test_get_workflow_metrics(self):
        """Test case for get_workflow_metrics

        """
        pass

    def test_get_workflow_template(self):
        """Test case for get_workflow_template

        """
        pass

    def test_get_workflow_template2(self):
        """Test case for get_workflow_template2

        """
        pass

    def test_list_workflow_template_versions(self):
        """Test case for list_workflow_template_versions

        """
        pass

    def test_list_workflow_templates(self):
        """Test case for list_workflow_templates

        """
        pass

    def test_list_workflows(self):
        """Test case for list_workflows

        """
        pass

    def test_resubmit_workflow(self):
        """Test case for resubmit_workflow

        """
        pass

    def test_terminate_workflow(self):
        """Test case for terminate_workflow

        """
        pass

    def test_update_workflow_template_version(self):
        """Test case for update_workflow_template_version

        """
        pass

    def test_watch_workflow(self):
        """Test case for watch_workflow

        """
        pass


if __name__ == '__main__':
    unittest.main()
