# coding: utf-8

"""
    metric.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import core.api
from core.api.models.get_workflow_metrics_response import GetWorkflowMetricsResponse  # noqa: E501
from core.api.rest import ApiException

class TestGetWorkflowMetricsResponse(unittest.TestCase):
    """GetWorkflowMetricsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test GetWorkflowMetricsResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = core.api.models.get_workflow_metrics_response.GetWorkflowMetricsResponse()  # noqa: E501
        if include_optional :
            return GetWorkflowMetricsResponse(
                metrics = [
                    core.api.models.metric.Metric(
                        name = '0', 
                        value = 1.337, 
                        format = '0', )
                    ]
            )
        else :
            return GetWorkflowMetricsResponse(
        )

    def testGetWorkflowMetricsResponse(self):
        """Test GetWorkflowMetricsResponse"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
