# coding: utf-8

"""
    Onepanel

    Onepanel API  # noqa: E501

    The version of the OpenAPI document: 0.12.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import onepanel.core.api
from onepanel.core.api.api.config_service_api import ConfigServiceApi  # noqa: E501
from onepanel.core.api.rest import ApiException


class TestConfigServiceApi(unittest.TestCase):
    """ConfigServiceApi unit test stubs"""

    def setUp(self):
        self.api = onepanel.core.api.api.config_service_api.ConfigServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_config(self):
        """Test case for get_config

        """
        pass


if __name__ == '__main__':
    unittest.main()
