# coding: utf-8

"""
    Onepanel

    Onepanel API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from onepanel.core.api.configuration import Configuration


class Predictor(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'node_selector': 'NodeSelector',
        'server': 'PredictorServer'
    }

    attribute_map = {
        'node_selector': 'nodeSelector',
        'server': 'server'
    }

    def __init__(self, node_selector=None, server=None, local_vars_configuration=None):  # noqa: E501
        """Predictor - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._node_selector = None
        self._server = None
        self.discriminator = None

        if node_selector is not None:
            self.node_selector = node_selector
        if server is not None:
            self.server = server

    @property
    def node_selector(self):
        """Gets the node_selector of this Predictor.  # noqa: E501


        :return: The node_selector of this Predictor.  # noqa: E501
        :rtype: NodeSelector
        """
        return self._node_selector

    @node_selector.setter
    def node_selector(self, node_selector):
        """Sets the node_selector of this Predictor.


        :param node_selector: The node_selector of this Predictor.  # noqa: E501
        :type: NodeSelector
        """

        self._node_selector = node_selector

    @property
    def server(self):
        """Gets the server of this Predictor.  # noqa: E501


        :return: The server of this Predictor.  # noqa: E501
        :rtype: PredictorServer
        """
        return self._server

    @server.setter
    def server(self, server):
        """Sets the server of this Predictor.


        :param server: The server of this Predictor.  # noqa: E501
        :type: PredictorServer
        """

        self._server = server

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Predictor):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Predictor):
            return True

        return self.to_dict() != other.to_dict()
